Item 구현
sandolee/KW-2021-team-project pull request #10
Opened 2021-05-04 08:57 UTC by nh0317

체력 증가 아이템과 무적 아이템 구현했습니다. 
player의 y축 움직임을 주석으로 추가해두었습니다. 혹시 테스트시 필요하시면 사용하시면 됩니다. 

수정사항이 있다면 알려주세요

2021-05-06 19:13 UTC, onebone requested changes

2021-05-06 19:13 UTC, onebone commented on Galaga/Entity/Player.cs
> +        public int GodModeStartTic { get; set; }
GodMode 변수와 GodModeStartTick 변수는 하나의 클래스에 같이 넣어두고 StartGodMode() 같은 함수를 통해 무적 상태를 시작하는 편이 나을 것 같습니다

2021-05-06 19:13 UTC, onebone commented on Galaga/Entity/Entity.cs
> +        public int Health { get; set; }
개인적인 의견이지만 Health의 접근 제한자를 바꿔서 다른 클래스에서 접근하는 것을 허용하는 대신, `Heal()`, `Kill()` 같은 함수를 만들어서 호출하는 게 좋을 것 같습니다

2021-05-09 03:25 UTC, joehyeonmin approved these changes

2021-05-09 03:40 UTC, onebone approved these changes

2021-05-09 03:40 UTC, merged