Score Implement
sandolee/KW-2021-team-project pull request #12
Opened 2021-05-13 09:18 UTC by nh0317

점수 구현했습니다.
Entity에서 Game에 접근하기 어려울 것 같아 World에 구현했습니다.

score는 피격시 10점 획득으로 구현했습니다.

2021-05-15 09:25 UTC, onebone requested changes

2021-05-15 09:25 UTC, onebone commented on Galaga/Game/World.cs
> +        private int score;
World에서 점수를 관리하는 형태는 World 클래스가 본래 역할 이외의 것을 하고 있는 느낌입니다. 제가 생각하기에 점수를 관리하기에 가장 적합한 곳은 Game 클래스인데, Entity에서는 Game 인스턴스에 접근하기가 어렵다고 하셔서 제가 생각한 다른 접근법을 알려드리고자 합니다:

- Entity가 직접 점수를 수정하는 형태가 아니라, Game에서 엔티티가 체력이 깎이는 상황을 감시한 후 점수를 수정합니다.
  - 이런 형태는 C#의 delegate 혹은 event로 구현할 수 있습니다. 현재 EntityManager의 OnKillDelegate는 엔티티가 죽었을 때 호출하는 이벤트 핸들러를 관리하는데, 이런 방식으로 구현하면 좋을 것 같습니다. Game에서 EntityManager로 접근하는 것은 가능하기 때문에 구현하는 데 큰 문제는 없을 것이라고 예상합니다.
  - 축구 경기를 예로 들었을 때, 골을 넣은 선수가 직접 점수를 수정하는 것보다는 경기를 보고 있는 심판이 점수를 올리는 것이 자연스럽습니다.

2021-05-15 09:25 UTC, onebone commented on Galaga/Entity/Entity.cs
> +            this.World.AddScore(10);
Player도 Entitiy를 상속 받기 때문에 플레이어가 대미지를 입는 상황에서도 점수가 올라갈 수 있습니다.

2021-05-15 09:25 UTC, onebone commented on Galaga/Form1.cs
> +        private string ID;
저희 프로젝트의 private field 명명법과 일치하도록 _id로 바꾸는 게 좋을 것 같습니다

2021-05-15 10:37 UTC, joehyeonmin approved these changes

2021-05-15 11:30 UTC, onebone commented
코드를 확인해보니 엔티티가 공격을 받으면 자신이 공격 받았다는 것을 마킹해두고 다음 틱에 점수를 반영하는 방식인데, 가독성 같은 문제를 생각한다면 아무래도 delegate 관련된 문서를 확인해보신 후에 다시 한 번 작성해보시는 게 좋지 않을까 합니다...!

delegate가 그렇게 복잡한 개념은 아니고, 단순하게 호출할 수 있는 함수를 변수에 저장할 수 있게 해주는 기능입니다. 이걸 이용해서 Game 클래스가 엔티티의 체력이 깎였을 때 하고 싶은 동작을 정의해둔 delegate를 EntityManager에 등록을 해두면 체력이 깎일 때 (Game 클래스에 저장되어 있는) 점수를 올릴 수 있겠다가 기본적인 아이디어입니다.

레포를 보니 안드로이드를 연습해보신 것 같아서 그걸 통해 설명을 해드리자면,
```java
findViewById(R.id.button).setOnClickListener(v -> {
    Toast.makeToast(this, "클릭", Toast.LENGTH_SHORT).show();
});
```
위의 코드와 같이 클릭하면 토스트를 발생시키라는 동작을 정의해서 View에 전달한 다음, 실제로 클릭이 되면 View가 등록된 리스너를 호출해서 토스트를 발생시킵니다.

비슷하게 여기서도:
> Galaga/Game/Game.cs
```c#
GetWorld().EntityManager.OnEntityAttack.Add(entity => {
    if(entity is Enemy) {
        _score += /* 점수 */;
    }
});
```
> Galaga/Game/EntityManager.cs
```c#
public delegate void OnEntityAttackDelegate(Entity entity, int damage);
public readonly List<OnEntityAttackDelegate> OnEntityAttack = new List<OnEntityAttackDelegate>();

// ...
public void Attack(int damage) {
    // ...
    OnEntityAttack.ForEach(del => del(this, damage)); // 엔티티가 공격을 받으면 등록된 리스너를 호출
}
```
과 같이 할 수 있습니다.

좀 더 빨리 확인을 했었어야 했는데 죄송합니다 ㅠㅠ

2021-05-16 03:26 UTC, onebone approved these changes

2021-05-16 03:34 UTC, merged