Add Create File
sandolee/KW-2021-team-project pull request #6
Opened 2021-05-02 04:10 UTC by nh0317

파일이 없는 경우 파일을 생성하도록 수정했습니다.

또한 디자이너보기에서 에러가 발생하는 듯 하여 using Galaga.Ui 추가했습니다.

2021-05-02 10:46 UTC, onebone requested changes

2021-05-02 10:46 UTC, onebone commented on Galaga/FileAccess/FileAccess.cs
> +        static String directoryPath = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "..", "..", "PlayerInfo"));
디렉토리와 파일의 관계가 의존적이라면 각각 모든 경로를 지정하기보단 아래처럼 디렉토리 경로를 이용해서 파일 경로를 생성하는 편이 나을 것 같습니다:

```c#
static string DirectoryPath = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "..", "..", "PlayerInfo"));
static string FilePath = Path.Combine(directoryPath, "PlayerInfo.csv");
```

2021-05-02 10:46 UTC, onebone commented on Galaga/SignUp.cs
> +            FileAccess.FileAccess.CreateInfo();
ReadInfo()를 호출할 때 파일이 없으면 오류가 나기를 바라는 상황은 없을 가능성이 높기 때문에 호출하는 쪽에서 CreateInfo()를 호출하기보단 ReadInfo()에서 직접 호출하는 편이 나을 것 같습니다

2021-05-08 10:03 UTC, onebone approved these changes

2021-05-09 03:23 UTC, joehyeonmin approved these changes

2021-05-09 03:34 UTC, merged